apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  annotations:
    nais.io/run-as-user: "1001"
  labels:
    team: {{ team }}
  name: {{ app }}
  namespace: {{ namespace }}
spec:
  image: {{ image }}
  port: 8080
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  ingresses:
  {{#each ingresses as |url|}}
    - {{ url }}
  {{/each}}
  replicas:
    max: 1
    min: 0
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
      {{#each externalHost as |host|}}
         - host: {{ host }}
      {{/each}}
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
