name: Build
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.dockerignore'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4

      - name: Sett opp pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Sett opp node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Installer avhengigheter
        run: pnpm install

      - name: Bygg koden
        run: pnpm run build