name: Build
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      READER_TOKEN:
        required: true
  pull_request:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.dockerignore'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Sett opp node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Installer avhengigheter
        run: yarn install --immutable

      - name: Bygg koden
        run: yarn run build