name: Deploy
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.dockerignore'
    branches:
      - main

env:
  IMAGE: europe-north1-docker.pkg.dev/${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}/helseopplysninger/${{ github.event.repository.name }}

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build:
    uses: ./.github/workflows/build.yml

  docker-build:
    runs-on: ubuntu-latest
    needs: [ lint, build ]
    permissions:
      packages: write
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4

      - name: Setter tag-navn
        run: echo "TAG=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          tag: ${{ env.TAG }}
          team: helseopplysninger
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
      contents: write
      id-token: write
    environment: dev-gcp:helseopplysninger
    env:
      PRINT_PAYLOAD: true
      TIMEOUT: 10m
      RESOURCE: .nais/app.yaml
      CLUSTER: dev-gcp
      VARS: nais/dev-gcp.json
      IMAGE: ${{ needs.docker-build.outputs.image }}
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4

      - name: Distribuer til dev
        uses: nais/deploy/actions/deploy@v2