name: Build and deploy
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows.lint.yml

  build:
    runs-on: ubuntu-latest
    needs: [ lint ]
    permissions:
      packages: write
      contents: read
      id-token: write
    outputs:
      image: &{{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install

      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: helseopplysninger
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: [ build ]
    environment: dev-gcp
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          PRINT_PAYLOAD: true
          RESOURCE: .nais/app.yaml
          VAR: version=${{ github.sha }},${{ needs.build.outputs.image }}