name: Lint

on:
  workflow_call:
    secrets:
      READER_TOKEN:
        required: true
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4

      - name: Sett opp pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Sett opp node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Installer avhengigheter
        run: pnpm install

      - name: Kjør lint
        run: pnpm run lint