name: Lint

on:
  workflow_call:
    secrets:
      READER_TOKEN:
        required: true
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Sett opp node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Installer avhengigheter
        run: yarn install --immutable

      - name: Kjør lint
        run: yarn lint

      - name: Sjekk typer
        run: yarn tsc